### ISSUE TITLE
Run tests without starting the server

### ISSUE THREAD

**Issue by sonip1992** [mauriciolauffer/wdio-qunit-service#10]
@mauriciolauffer: Since our UI5 projects have *qunit.html files, wdio requires application server for our qunits to run.

While i did try [static-server-service](https://webdriver.io/docs/static-server-service) and it did not work, i was wondering if there is a way we can run our qunits in pipeline like karma does without the need of starting the server?

**Comment by mauriciolauffer** [comment]
`WebdriverIO` doesn't support it, and this service is an extension of it, therefore starting a server is not possible. You must start the server before running the tests, something like https://www.npmjs.com/package/start-server-and-test helps with that.
