### ISSUE TITLE
Unable to use any logs in tests

### ISSUE THREAD

**Issue by azehintense** [mauriciolauffer/wdio-qunit-service#11]
Logs from the entrypoint where getQUnitResults is called are displayed but i can't get logs from within the tests to work. This is a huge problem as one test is miraculously failing since i replaced karma with this test and all i get is a "false" since the service reduces a test on a object to a boolean test in QUnitResults. 

How can i get the logs to work? Am i doing something wrong?

**Comment by azehintense** [comment]
nvm browser.getLogs worked

**Comment by mauriciolauffer** [comment]
Hi @azehintense,

I'm curious to know whether you fixed the failing test. What was the problem?

**Comment by azehintense** [comment]
@mauriciolauffer Yeah i fixed it :) The old karma solution ignored the default locale and used karmas default which is english but our app is in german. Now with your service german is used and so one expected text could finally be changed to it's german text :)
