### ISSUE TITLE
QUnit tests that are not in a module are ignored by the service

### ISSUE THREAD

**Issue by bburke4** [mauriciolauffer/wdio-qunit-service#12]
The `generateTestCases` function only looks at tests in `childSuites`: 
https://github.com/mauriciolauffer/wdio-qunit-service/blob/48c10ba8398fc9406032f5fea24e71e4b985f7c9/src/index.ts#L43C10-L43C27

I have a test file where only one of the four tests is defined under a module. The resulting `qunitResults` data structure looks like this:

```
[0-0] 2024-05-29T21:11:54.390Z INFO webdriver: RESULT {
[0-0]   childSuites: [
[0-0]     {
[0-0]       childSuites: [],
[0-0]       fullName: [Array],
[0-0]       name: 'violations-test-module',
[0-0]       runtime: 4031,
[0-0]       status: 'passed',
[0-0]       testCounts: [Object],
[0-0]       tests: [Array]
[0-0]     }
[0-0]   ],
[0-0]   fullName: [],
[0-0]   name: null,
[0-0]   runtime: 11128,
[0-0]   status: 'failed',
[0-0]   testCounts: { failed: 2, passed: 4, skipped: 0, todo: 0, total: 6 },
[0-0]   tests: [
[0-0]     {
[0-0]       assertions: [Array],
[0-0]       errors: [],
[0-0]       fullName: [Array],
[0-0]       name: 'qoe-stuff',
[0-0]       runtime: 1003,
[0-0]       status: 'passed',
[0-0]       suiteName: null
[0-0]     },
[0-0]     {
[0-0]       assertions: [Array],
[0-0]       errors: [],
[0-0]       fullName: [Array],
[0-0]       name: 'js-error-stuff',
[0-0]       runtime: 3125,
[0-0]       status: 'passed',
[0-0]       suiteName: null
[0-0]     },
[0-0]     {
[0-0]       assertions: [Array],
[0-0]       errors: [],
[0-0]       fullName: [Array],
[0-0]       name: 'qoe-loaded',
[0-0]       runtime: 2968,
[0-0]       status: 'passed',
[0-0]       suiteName: null
[0-0]     }
[0-0]   ]
[0-0] }
```

Only the test in childSuites was processed.

**Comment by mauriciolauffer** [comment]
@bburke4 thanks for sharing it. I've run a couple tests with no qunit modules and couldn't replicate your issue. Would be possible to share a gist/repo with your scenario, pls?

**Comment by mauriciolauffer** [comment]
I could replicate this [function](https://github.com/mauriciolauffer/wdio-qunit-service/blob/48c10ba8398fc9406032f5fea24e71e4b985f7c9/src/index.ts#L51) at a higher level in the code, which probably would fix your issue. I just want to replicate it before making any changes.

I'll also include the scenario to the [examples/tests](https://github.com/mauriciolauffer/wdio-qunit-service/tree/main/examples/openui5-sample-app/webapp/test/unit)

**Comment by bburke4** [comment]
Thanks for the quick reply. I will work on modifying my tests in such a way that I can share them publicly. But FWIW, the tests were written out in a script tag in an html file and I was loading QUnit via http://code.jquery.com/qunit/qunit-2.20.1.js

**Comment by bburke4** [comment]
It seems to be related to async tests. Here is the test file that should reproduce it:
```html
<html>
    <head>
        <title> Tests</title>
        <link rel="stylesheet" href="//code.jquery.com/qunit/qunit-2.20.1.css">
    </head>
    <body>
        <div id="qunit"></div>
        <div id="qunit-fixture"></div>
        <script src="//code.jquery.com/jquery.js"></script>
        <script src="//code.jquery.com/qunit/qunit-2.20.1.js"></script>
        <script>
      function runTests() {
        QUnit.test("test 1", function (assert) {
          var done = assert.async();
          setTimeout(function() {
            assert.ok(true, "Passed!");
            done();
          }, 1000);
        });

        QUnit.module('module 1')

        QUnit.test("test 2", function(assert) {
          assert.ok(true, "Passed!");
        });
      }
      runTests();
        </script>
    </body>
</html>
```

Test file was simple:
```JavaScript
    describe('Unit Tests', () => {
        it('should pass', async () => {
            await browser.url('http://localhost/sample-test.html');
            const qunitResults = await browser.getQUnitResults();
            expect(qunitResults).toBeTruthy();
        });
    });
```

Thanks!

**Comment by bburke4** [comment]
On a potentially unrelated note, I also ran into an issue of tests being ignored when i was loading some asynchronously. I noticed that the service was detecting that the `runEnd` must have already been emitted so it collected the results before all the tests had finished running.

Looking into the code a bit, I was wondering if it would be better if the service checked `QUnit.config.pq.finished` instead of `QUnit.config.queue.length` [here](https://github.com/mauriciolauffer/wdio-qunit-service/blob/48c10ba8398fc9406032f5fea24e71e4b985f7c9/src/index.ts#L24), but I haven't tested this out yet.

**Comment by mauriciolauffer** [comment]
@bburke4 thanks for sharing all these details, I appreciate it. Both issues should be fixed now (https://github.com/mauriciolauffer/wdio-qunit-service/pull/13). I've also included more tests that should cover these scenarios.

**Comment by mauriciolauffer** [comment]
@bburke4  thanks for sharing all these details, I appreciate it. Both issues should be fixed now (https://github.com/mauriciolauffer/wdio-qunit-service/pull/13). I've also included more tests that should cover these scenarios.

**Comment by bburke4** [comment]
Thanks so much @mauriciolauffer! I see all of my tests included in the results now and it even seems to run a little quicker. Thank you!
