### ISSUE TITLE
Failed to load sap/ui/core/SortOrder.js when running OPA5 Tests with the wdio-qunit-service

### ISSUE THREAD

**Issue by meindla** [mauriciolauffer/wdio-qunit-service#5]
**Describe the bug**
We are running OPA5 tests using the OPA5 Test library for Fiori Elements V4 and the wdio-qunit-service.
The sap resources are served statically by the tooling extension ui5-middleware-servestatic. The resources are downloaded from https://tools.hana.ondemand.com/#sapui5.
Starting the test results in following error:
![image](https://github.com/mauriciolauffer/wdio-qunit-service/assets/121859054/9b9bec21-5429-404b-9a4e-38740619054b)

In the opaTests.qunit.html, I reference the static resources:
![image](https://github.com/mauriciolauffer/wdio-qunit-service/assets/121859054/f934aa12-9332-4f9d-a1d7-adf7c3579501)

Following the dependencies in the error log
-> 'sap/fe/test/ListReport.js'
-> 'sap/fe/test/TemplatePage.js'
-> 'sap/fe/test/builder/MdcTableBuilder.js'
-> 'sap/ui/core/SortOrder.js'
I wonder where I can find the SortOrder.js in the sap/ui/core folder. There is no such file.
Using the resources from https://sapui5.hana.ondemand.com/resources/sap-ui-core.js, I don´t get the error, although I
use the same UI5 verison (1.120.0).

When I start the server, open the Browser and open opaTests.qunit.html, I dont get the error.

Could you help here?
Why is the SortOrder.js file missing in the sap/ui/core folder?

**Expected behavior**
I expect the ui5 resouces correctly loaded.

**Runtime Env (please complete the following information):**

UI5 version: 1.120.0
wdio-qunit-service version: 0.1.1
wdio-version (output of wdio --version): 8.26.1
node-version (output of node --version): 18.16.1
Browser + Version: Chrome 120.0.6099.71

**Comment by mauriciolauffer** [comment]
Hi there, this is an odd one as the service just opens opaTests.qunit.html in the browser, it doesn't inject anything nor try loading assets.
Could you provide an example in a git repo where I can reproduce the error?
