### ISSUE TITLE
Issue runing tests

### ISSUE THREAD

**Issue by RichieF5** [mauriciolauffer/wdio-qunit-service#9]
I downloaded your git repo and ran npm install wdio-qunit-service --save-dev.

But when I try to execute the tests "npm run test" I get the following error

Error: Error: Failed to initilialise launcher service unknown: Error: Couldn't find plugin "qunit" service, neither as wdio scoped package "@wdio/qunit-service" nor as community package "wdio-qunit-service". Please make sure you have it installed!

Any ideas what I'm doing wrong?

**Comment by mauriciolauffer** [comment]
You don't need to download the git repo to install the npm package. Just run `npm install wdio-qunit-service` from the folder the `package.json` file is located.

I haven't had any issues installing it. The NPM package is published here: https://www.npmjs.com/package/wdio-qunit-service
